swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/accounts/{accountID}/transactions/{year}/{month}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Get Transactions for the Current Month by Account
      description: Get all transactions for the current month, grouped by account
      parameters:
        - name: accountID
          in: path
          required: true
          description: ID of the user's bank account
          type: string
        - name: year
          in: path
          required: true
          description: Year (e.g., 2023)
          type: integer
        - name: month
          in: path
          required: true
          description: Month (1-12)
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: User bank account transactions for the current month successfully retrieved
          schema:
            $ref: "#/definitions/UserAccountTransactions"
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error

  /user/accounts/{accountID}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: API transactions of a user's bank account
      description: User bank account transaction list retrieval API
      parameters:
        - in: path
          name: accountID
          description: ID of the user's bank account
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User bank account transactions successfully recovered
          schema:
            $ref: "#/definitions/UserAccountTransactions"
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
  /user/accounts/{accountID}/transactions/{transactionID}:
    patch:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update Category and Note of a Transaction
      description: Update the category and note of a user's bank account transaction using transactionID
      parameters:
        - name: accountID
          in: path
          required: true
          description: ID of the user's bank account
          type: string
        - name: transactionID
          in: path
          required: true
          description: ID of the user's bank account transaction
          type: string
        - in: body
          name: body
          description: Category and Note Payload
          required: true
          schema:
            type: object
            properties:
              category:
                type: string
                description: transaction category
              note:
                type: string
                description: transaction note
      produces:
        - application/json
      responses:
        "204":
          description: User bank account transaction category and note successfully updated (No content)
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  UserAccounts:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        amount:
          type: string
        description:
          type: string
    minItems: 3
    maxItems: 3
  Transaction:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
      description:
        type: string
      amount:
        type: string
      balance:
        type: string
      transaction_type:
        type: string
      category:
        type: string
      note:
        type: string
  UserAccountTransactions:
    type: array
    items:
      $ref: "#/definitions/Transaction"
    minItems: 3
  Category:
    properties:
      category:
        type: string
        description: transaction category
  Note:
    properties:
      note:
        type: string
        description: transaction note
